bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_box.h -o fltk-sys/src/frame.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_button.h -o fltk-sys/src/button.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_group.h -o fltk-sys/src/group.rs 
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_text.h -o fltk-sys/src/text.rs 
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_input.h -o fltk-sys/src/input.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_widget.h -o fltk-sys/src/widget.rs
bindgen --use-core --no-layout-tests fltk-sys/cfltk/include/cfltk2/cfl_window.h -o fltk-sys/src/window.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_menu.h -o fltk-sys/src/menu.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_dialog.h -o fltk-sys/src/dialog.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_valuator.h -o fltk-sys/src/valuator.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_browser.h -o fltk-sys/src/browser.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_image.h -o fltk-sys/src/image.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_misc.h -o fltk-sys/src/misc.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_draw.h -o fltk-sys/src/draw.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_table.h -o fltk-sys/src/table.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_tree.h -o fltk-sys/src/tree.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl.h -o fltk-sys/src/fl.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_surface.h -o fltk-sys/src/surface.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_printer.h -o fltk-sys/src/printer.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_utils.h -o fltk-sys/src/utils.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_prefs.h -o fltk-sys/src/prefs.rs
bindgen --use-core fltk-sys/cfltk/include/cfltk2/cfl_term.h -o fltk-sys/src/term.rs
