/* automatically generated by rust-bindgen 0.56.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Fl_Surface_Device {
    _unused: [u8; 0],
}
extern "C" {
    pub fn Fl_Surface_Device_set_current(self_: *mut Fl_Surface_Device);
}
extern "C" {
    pub fn Fl_Surface_Device_is_current(self_: *mut Fl_Surface_Device) -> libc::c_int;
}
extern "C" {
    pub fn Fl_Surface_Device_surface() -> *mut Fl_Surface_Device;
}
extern "C" {
    pub fn Fl_Surface_Device_push_current(new_current: *mut Fl_Surface_Device);
}
extern "C" {
    pub fn Fl_Surface_Device_pop_current() -> *mut Fl_Surface_Device;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Fl_Image_Surface {
    _unused: [u8; 0],
}
extern "C" {
    pub fn Fl_Image_Surface_new(
        w: libc::c_int,
        h: libc::c_int,
        high_res: libc::c_int,
    ) -> *mut Fl_Image_Surface;
}
extern "C" {
    pub fn Fl_Image_Surface_delete(s: *mut Fl_Image_Surface);
}
extern "C" {
    pub fn Fl_Image_Surface_set_current(self_: *mut Fl_Image_Surface);
}
extern "C" {
    pub fn Fl_Image_Surface_is_current(self_: *mut Fl_Image_Surface) -> libc::c_int;
}
extern "C" {
    pub fn Fl_Image_Surface_image(self_: *mut Fl_Image_Surface) -> *mut libc::c_void;
}
extern "C" {
    pub fn Fl_Image_Surface_highres_image(self_: *mut Fl_Image_Surface) -> *mut libc::c_void;
}
extern "C" {
    pub fn Fl_Image_Surface_origin(
        self_: *mut Fl_Image_Surface,
        x: *mut libc::c_int,
        y: *mut libc::c_int,
    );
}
extern "C" {
    pub fn Fl_Image_Surface_set_origin(
        self_: *mut Fl_Image_Surface,
        x: libc::c_int,
        y: libc::c_int,
    );
}
extern "C" {
    pub fn Fl_Image_Surface_rescale(self_: *mut Fl_Image_Surface);
}
extern "C" {
    pub fn Fl_Image_Surface_draw(
        self_: *mut Fl_Image_Surface,
        widget: *mut libc::c_void,
        delta_x: libc::c_int,
        delta_y: libc::c_int,
    );
}
extern "C" {
    pub fn Fl_Image_Surface_draw_decorated_window(
        self_: *mut Fl_Image_Surface,
        widget: *mut libc::c_void,
        delta_x: libc::c_int,
        delta_y: libc::c_int,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Fl_SVG_File_Surface {
    _unused: [u8; 0],
}
extern "C" {
    pub fn Fl_SVG_File_Surface_new(
        width: libc::c_int,
        height: libc::c_int,
        file: *const libc::c_char,
    ) -> *mut Fl_SVG_File_Surface;
}
extern "C" {
    pub fn Fl_SVG_File_Surface_delete(self_: *mut Fl_SVG_File_Surface);
}
extern "C" {
    pub fn Fl_SVG_File_Surface_origin(
        self_: *mut Fl_SVG_File_Surface,
        x: libc::c_int,
        y: libc::c_int,
    );
}
extern "C" {
    pub fn Fl_SVG_File_Surface_printable_rect(
        self_: *mut Fl_SVG_File_Surface,
        w: *mut libc::c_int,
        h: *mut libc::c_int,
    ) -> libc::c_int;
}
extern "C" {
    pub fn Fl_SVG_File_Surface_draw(
        self_: *mut Fl_SVG_File_Surface,
        widget: *mut libc::c_void,
        delta_x: libc::c_int,
        delta_y: libc::c_int,
    );
}
extern "C" {
    pub fn Fl_SVG_File_Surface_draw_decorated_window(
        self_: *mut Fl_SVG_File_Surface,
        widget: *mut libc::c_void,
        delta_x: libc::c_int,
        delta_y: libc::c_int,
    );
}
