/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn Fl_filename_expand(
        out: *mut ::core::ffi::c_char,
        len: ::core::ffi::c_int,
        in_: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn Fl_type_name(w: *mut ::core::ffi::c_void) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn Fl_open_uri(
        uri: *const ::core::ffi::c_char,
        msg: *mut ::core::ffi::c_char,
        msglen: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn Fl_decode_uri(uri: *mut ::core::ffi::c_char);
}
