/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    pub fn Fl_filename_expand(
        out: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        in_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn Fl_type_name(w: *mut ::std::os::raw::c_void) -> *const ::std::os::raw::c_char;
}
