/* automatically generated by rust-bindgen 0.56.0 */

extern "C" {
    pub fn Fl_filename_expand(
        out: *mut libc::c_char,
        len: libc::c_int,
        in_: *const libc::c_char,
    ) -> libc::c_int;
}
