/* automatically generated by rust-bindgen */

pub type cfl_window = ::std::os::raw::c_void;
extern "C" {
    pub fn cfl_window_new(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        title: *const ::std::os::raw::c_char,
    ) -> *mut cfl_window;
}
extern "C" {
    pub fn cfl_window_end(arg1: *mut cfl_window);
}
extern "C" {
    pub fn cfl_window_show(arg1: *mut cfl_window);
}
